import { CSSProperties, FormEvent, KeyboardEvent as ReactKeyboardEvent, ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  AlertTriangle, Archive, ArrowRight, ArrowUp, ArrowUpRight, Bookmark, Check, CheckCircle2, ChevronDown, Circle, Clock3,
  Download, Edit3, Feather, CircleHelp, FileInput, Figma, Github, History, Layers3, Link2, Loader2, MessageCircleMore,
  Plus, RotateCcw, Search, Settings2, ShieldCheck, Trash2, X
} from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import Onboarding from './Onboarding';
import BrandMark from './BrandMark';
import { studioApi, type Bootstrap, type Diagnostics } from './lib/studioApi';
import type { ArtifactType, MemoryArtifact, SearchResult, StudioProject, StudioSession, StudioSource, TimelineEvent } from './lib/creativeMemory';

type Surface='studio'|'memory'|'history';
type ReviewHandler=(id:string,action:'accept'|'reject',supersedeIds?:string[])=>Promise<void>|void;
type Dialog=null|'project'|'session'|'source'|'import'|'settings';
const artifactIcons:Record<ArtifactType,string>={decision:'✓',principle:'✦',question:'?',idea:'◌',experiment:'○',reference:'↗',risk:'!',action:'→',abandoned:'×'};
const colors=['#9E4935','#3F665A','#48627E','#8B6A44','#776057','#6B6984'];
const ACTIVE_PROJECT_KEY='remainder-active-project-v1';

function relativeDate(value:string){
  const diff=Date.now()-new Date(value).getTime();const day=Math.floor(diff/86400000);
  if(day<=0)return 'Today';if(day===1)return 'Yesterday';if(day<7)return day+' days ago';
  return new Date(value).toLocaleDateString([], {month:'short',day:'numeric'});
}
function artifactClass(type:ArtifactType){return type==='decision'?'decision':type==='principle'?'principle':type==='question'?'question':type==='risk'?'risk':'experiment'}

function Sidebar({data,surface,onSurface,onProject,onNewProject,onSettings}:{
  data:Bootstrap;surface:Surface;onSurface:(value:Surface)=>void;onProject:(id:string)=>void;onNewProject:()=>void;onSettings:()=>void
}){
  const nav=[{id:'studio' as const,label:'Conversation',icon:MessageCircleMore},{id:'memory' as const,label:'Memory',icon:Archive},{id:'history' as const,label:'History',icon:History}];
  const accepted=data.artifacts.filter(item=>item.reviewStatus==='accepted'&&item.status!=='archived').length;const pending=data.artifacts.filter(item=>item.reviewStatus==='pending').length;
  return <aside className="sidebar">
    <div className="sidebar-top"><BrandMark aria-label="Remainder"/></div>
    <nav className="primary-nav" aria-label="Workspace">{nav.map(({id,label,icon:Icon})=><button key={id} className={surface===id?'nav-item active':'nav-item'} aria-current={surface===id?'page':undefined} onClick={()=>onSurface(id)}><Icon size={17}/><span>{label}</span>{id==='memory'&&<span className={'nav-count '+(pending?'has-review':'')} title={pending?pending+' awaiting review':''}>{accepted}{pending?' +'+pending:''}</span>}</button>)}</nav>
    <div className="sidebar-projects">
      <div className="sidebar-label"><span>Projects</span><button aria-label="New project" onClick={onNewProject}><Plus size={13}/></button></div>
      {data.projects.map(project=><button key={project.id} className={project.id===data.project.id?'project-nav active':'project-nav'} aria-current={project.id===data.project.id?'true':undefined} onClick={()=>onProject(project.id)}>
        <span className="project-sigil" style={{'--project-color':project.color} as CSSProperties}>{project.name[0]}</span><span className="project-name">{project.name}</span>{project.id===data.project.id&&<span className="live-dot"/>}
      </button>)}
    </div>
    <div className="sidebar-footer"><button className="profile-button" onClick={onSettings}><span className="avatar">TS</span><span><strong>Personal workspace</strong><small>What matters, remains</small></span><Settings2 size={13}/></button></div>
  </aside>
}

function Topbar({data,session,onSearch,onSettings,onHelp,onProject,onNewProject}: {data:Bootstrap;session:StudioSession|null;onSearch:()=>void;onSettings:()=>void;onHelp:()=>void;onProject:(id:string)=>void;onNewProject:()=>void}){
  return <header className="topbar">
    <div className="topbar-project"><label className="project-switcher"><span className="project-dot" style={{background:data.project.color}}/><span className="sr-only">Current project</span><select aria-label="Switch project" value={data.project.id} onChange={event=>onProject(event.target.value)}>{data.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><ChevronDown size={12}/></label><span className="topbar-context">/ {session?.title||'No conversation'}</span></div>
    <div className="topbar-actions">
      <span className={'sync-state '+(data.aiConfigured?'ai-on':'')}><span/>{data.aiConfigured?'NVIDIA NIM configured':'Local intelligence'}</span>
      <button className="search-button" onClick={onSearch}><Search size={14}/><span>Find anything</span><kbd>Ctrl K</kbd></button>
      <button type="button" className="icon-button topbar-new" aria-label="New project" title="New project" onClick={onNewProject}><Plus size={16}/></button><button type="button" className="icon-button topbar-help" aria-label="Open setup guide" title="Setup guide" onClick={onHelp}><CircleHelp size={16}/></button><button type="button" className="icon-button" aria-label="Settings" title="Settings" onClick={onSettings}><Settings2 size={16}/></button>
    </div>
  </header>
}

function SessionMenu({sessions,active,onSelect,onNew,onImport}:{
  sessions:StudioSession[];active:StudioSession|null;onSelect:(id:string)=>void;onNew:()=>void;onImport:()=>void
}){
  const [open,setOpen]=useState(false);const ref=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);
  const close=(restoreFocus=false)=>{setOpen(false);if(restoreFocus)window.setTimeout(()=>trigger.current?.focus(),0)};
  useEffect(()=>{if(!open)return;const pointer=(event:PointerEvent)=>{if(!ref.current?.contains(event.target as Node))close()};const key=(event:globalThis.KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close(true)}};document.addEventListener('pointerdown',pointer);window.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',pointer);window.removeEventListener('keydown',key)}},[open]);
  return <div className="session-switch" ref={ref} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))close()}}>
    <button ref={trigger} type="button" onClick={()=>setOpen(value=>!value)} onKeyDown={event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const direction=event.key;setOpen(true);window.setTimeout(()=>{const items=ref.current?.querySelectorAll<HTMLElement>('.session-menu button');items?.[direction==='ArrowUp'?items.length-1:0]?.focus()},0)}}} aria-expanded={open} aria-haspopup="menu"><span>{active?.title||'Start a conversation'}</span><ChevronDown size={13}/></button>
    <AnimatePresence>{open&&<motion.div className="session-menu" role="menu" aria-label="Conversations" onKeyDown={event=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();const items=Array.prototype.slice.call(event.currentTarget.querySelectorAll('button')) as HTMLButtonElement[];if(!items.length)return;const current=items.indexOf(document.activeElement as HTMLButtonElement);const next=current<0?(event.key==='ArrowUp'?items.length-1:0):event.key==='Home'?0:event.key==='End'?items.length-1:event.key==='ArrowDown'?(current+1)%items.length:(current-1+items.length)%items.length;items[next].focus()}} initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}}>
      <p>Conversations</p>{sessions.map(session=><button type="button" role="menuitem" key={session.id} className={active?.id===session.id?'active':''} onClick={()=>{onSelect(session.id);close(true)}}><MessageCircleMore size={13}/><span><strong>{session.title}</strong><small>{session.messages.length} messages &middot; {relativeDate(session.updatedAt)}</small></span></button>)}
      <div className="session-menu-actions"><button type="button" role="menuitem" onClick={()=>{onNew();setOpen(false)}}><Plus size={12}/>New</button><button type="button" role="menuitem" onClick={()=>{onImport();setOpen(false)}}><FileInput size={12}/>Import</button></div>
    </motion.div>}</AnimatePresence>
  </div>
}

function ContextRail({data,onSource,onArtifact,onMemory,onProject}: {data:Bootstrap;onSource:()=>void;onArtifact:(artifact:MemoryArtifact)=>void;onMemory:()=>void;onProject:(id:string)=>void}){
  const accepted=data.artifacts.filter(item=>item.reviewStatus==='accepted'&&item.status==='active');
  const pending=data.artifacts.filter(item=>item.reviewStatus==='pending');
  const currentQuestion=accepted.find(item=>item.type==='question');
  const recentDecisions=accepted.filter(item=>item.type==='decision').slice(0,2);
  const openThreads=accepted.filter(item=>(item.type==='question'&&item.id!==currentQuestion?.id)||item.type==='action').slice(0,3);
  const recentMemories=accepted.filter(item=>item.id!==currentQuestion?.id&&!recentDecisions.some(decision=>decision.id===item.id)).slice(0,3);
  const latestUserQuestion=data.sessions.flatMap(item=>item.messages).filter(item=>item.role==='user'&&item.content.includes('?')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];
  const focusTerms=new Set((data.project.name+' '+data.project.description+' '+accepted.map(item=>item.title).join(' ')).toLowerCase().split(/[^a-z0-9]+/).filter(term=>term.length>4));
  const relatedProjects=data.projects.filter(item=>item.id!==data.project.id).map(item=>({item,score:(item.name+' '+item.description).toLowerCase().split(/[^a-z0-9]+/).filter(term=>focusTerms.has(term)).length})).filter(entry=>entry.score>0).sort((a,b)=>b.score-a.score).slice(0,2).map(entry=>entry.item);
  const connection=accepted.find(item=>item.relatedArtifactIds.some(id=>data.artifacts.some(other=>other.id===id)));
  const connected=connection?data.artifacts.filter(item=>connection.relatedArtifactIds.includes(item.id)).slice(0,2):[];
  const artifactButton=(item:MemoryArtifact,label?:string)=><button className="context-item" key={item.id} onClick={()=>onArtifact(item)}><span className={'artifact-icon '+artifactClass(item.type)}>{artifactIcons[item.type]}</span><span><small>{label||item.type}</small>{item.title}</span></button>;
  return <aside className="context-rail" aria-label="Living project context">
    <div className="context-heading"><div><BrandMark compact/><span>In view</span></div><button onClick={onSource} aria-label="Add a project source" title="Add a project source"><Plus size={14}/></button></div>
    <section className="context-block context-focus"><p className="eyebrow">Current question</p>
      {currentQuestion?artifactButton(currentQuestion):latestUserQuestion?<blockquote>{latestUserQuestion.content}</blockquote>:<p className="empty-hint">Ask what still feels unresolved. Captured questions become a compass for the next conversation.</p>}
    </section>
    {pending.length>0&&<section className="context-block review-callout"><div><span>{pending.length}</span><p><strong>Memory awaiting judgment</strong><small>Choose what becomes part of the project.</small></p></div><button onClick={onMemory}>Review now<ArrowRight size={11}/></button></section>}
    <section className="context-block context-list"><p className="eyebrow">Recent decisions</p>
      {recentDecisions.length?recentDecisions.map(item=>artifactButton(item)):<p className="empty-hint">Decisions appear here once a captured direction is kept in memory.</p>}
    </section>
    <section className="context-block context-list"><p className="eyebrow">Open threads</p>
      {openThreads.length?openThreads.map(item=>artifactButton(item,item.type==='action'?'to-do':'question')):<p className="empty-hint">Open questions and next actions will gather here instead of disappearing into chat history.</p>}
    </section>
    {connection&&connected.length>0&&<section className="context-block context-list"><p className="eyebrow">Suggested connection</p><p className="connection-lede">“{connection.title}” may change an earlier direction.</p>{connected.map(item=>artifactButton(item,'related memory'))}</section>}
    <section className="context-block context-list"><p className="eyebrow">Recent memory</p>
      {recentMemories.length?recentMemories.map(item=>artifactButton(item)):<p className="empty-hint">Capture a conversation and keep what should travel with the project.</p>}
    </section>
    {relatedProjects.length>0&&<section className="context-block context-list"><p className="eyebrow">Related projects</p>{relatedProjects.map(project=><button className="related-project" key={project.id} onClick={()=>onProject(project.id)}><span className="project-sigil" style={{'--project-color':project.color} as CSSProperties}>{project.name[0]}</span><span><strong>{project.name}</strong><small>{project.description||'Open this project’s memory.'}</small></span><ArrowUpRight size={11}/></button>)}</section>}
    <div className="context-footnote"><Layers3 size={12}/><span>Context carries forward with the project</span></div>
  </aside>
}

function Composer({disabled,captureDisabled,thinking,onSend,onCapture}: {disabled:boolean;captureDisabled:boolean;thinking:boolean;onSend:(text:string)=>Promise<boolean>;onCapture:()=>void}){
  const [value,setValue]=useState('');const ref=useRef<HTMLTextAreaElement>(null);
  useEffect(()=>{const key=(event:globalThis.KeyboardEvent)=>{if(event.key==='/'&&!document.querySelector('[aria-modal="true"]')&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName||'')){event.preventDefault();ref.current?.focus()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
  const submit=async(event?:FormEvent)=>{event?.preventDefault();const draft=value.trim();if(!draft||disabled||thinking)return;const sent=await onSend(draft);if(sent)setValue(current=>current.trim()===draft?'':current)};
  return <div className="composer-wrap"><form className="composer" onSubmit={event=>void submit(event)} aria-busy={thinking}>
    <textarea aria-label="Write to Remainder" ref={ref} rows={2} value={value} disabled={disabled||thinking} onChange={event=>setValue(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void submit()}}} placeholder={disabled?'Start a conversation first…':'Continue the thought…'}/>
    <div className="composer-actions"><span className="composer-hint">Enter to send · Shift Enter for a new line</span><button type="submit" className={value.trim()?'send-button ready':'send-button'} disabled={disabled||thinking||!value.trim()} aria-label="Send message"><ArrowUp size={15}/></button></div>
  </form><div className="capture-row"><span>{thinking?'Following the thread…':captureDisabled?'A conversation becomes memory after the first exchange.':'Everything here stays with this project.'}</span><button type="button" className="capture-button" disabled={captureDisabled||thinking} onClick={onCapture}><BrandMark compact/><span>Keep from session</span><kbd>Ctrl Shift S</kbd></button></div></div>
}

function StudioView({data,session,thinking,onSend,onCapture,onSession,onNewSession,onImport,onSource,onArtifact,onMemory,onProject}:{
  data:Bootstrap;session:StudioSession|null;thinking:boolean;onSend:(text:string)=>Promise<boolean>;onCapture:()=>void;onSession:(id:string)=>void;onNewSession:()=>void;onImport:()=>void;onSource:()=>void;onArtifact:(artifact:MemoryArtifact)=>void;onMemory:()=>void;onProject:(id:string)=>void
}){
  const end=useRef<HTMLDivElement>(null);useEffect(()=>{const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;end.current?.scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest'})},[session?.messages.length,thinking]);
  const date=new Date();
  return <div className="studio-layout"><main id="main-content" tabIndex={-1} className="conversation"><div className="conversation-inner">
    <div className="studio-session-header"><div className="morning-note"><span className="date-mark">{date.toLocaleDateString([], {weekday:'short'}).toUpperCase()}<br/>{date.getDate()}</span><div><p>{data.project.name}</p><h1>{session?.messages.length?'Continue where the idea still has tension.':'What are you thinking about?'}</h1></div></div><SessionMenu sessions={data.sessions} active={session} onSelect={onSession} onNew={onNewSession} onImport={onImport}/></div>
    <div className="session-marker"><span/>{session?.title||'No conversation selected'}<span/></div>
    <div className="messages">
      {!session?.messages.length&&<div className="conversation-empty"><BrandMark/><p>Begin with an observation, a tension, or something you cannot yet name.</p></div>}
      {session?.messages.map(message=><motion.article initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} key={message.id} className={'message '+(message.role==='user'?'you':'studio')}>
        <div>{message.role==='user'?<span className="avatar small">YOU</span>:<span className="studio-avatar"><BrandMark compact/></span>}</div>
        <div className="message-content"><div className="message-meta"><strong>{message.role==='user'?'You':'Remainder'}</strong><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</time></div><p>{message.content}</p>
          {!!message.citedArtifactIds.length&&<div className="citation-row">{message.citedArtifactIds.map(id=>{const artifact=data.artifacts.find(item=>item.id===id);return artifact?<button key={id} onClick={()=>onArtifact(artifact)}><Bookmark size={10}/>{artifact.title}</button>:null})}</div>}
        </div>
      </motion.article>)}
      {thinking&&<div className="thinking" role="status" aria-label="Remainder is responding"><span aria-hidden="true"/><span aria-hidden="true"/><span aria-hidden="true"/></div>}<div ref={end}/>
    </div>
  </div><Composer disabled={!session} captureDisabled={!session||!session.messages.length} thinking={thinking} onSend={onSend} onCapture={onCapture}/></main><ContextRail data={data} onSource={onSource} onArtifact={onArtifact} onMemory={onMemory} onProject={onProject}/></div>
}

function MemoryView({data,onArtifact,onReview,onStudio}: {data:Bootstrap;onArtifact:(artifact:MemoryArtifact)=>void;onReview:ReviewHandler;onStudio:()=>void}){
  const [filter,setFilter]=useState<'all'|ArtifactType>('all');
  const pending=data.artifacts.filter(item=>item.reviewStatus==='pending');const accepted=data.artifacts.filter(item=>item.reviewStatus==='accepted'&&item.status!=='archived');
  const visible=accepted.filter(item=>filter==='all'||item.type===filter);
  const labels:Partial<Record<ArtifactType,string>>={decision:'Decisions',question:'Questions',principle:'Principles',experiment:'Experiments',action:'To-dos'};
  return <main id="main-content" tabIndex={-1} className="quiet-surface"><div className="surface-intro"><p className="eyebrow">{data.project.name} · {accepted.length} durable {accepted.length===1?'memory':'memories'}</p><h1>The project remembers<br/>how it became itself.</h1><p>Decisions, principles, questions, experiments, and abandoned directions remain connected to where they came from.</p></div>
    {pending.length>0&&<section className="review-inbox" aria-label="Memory awaiting review"><div className="review-heading"><div><p className="eyebrow">Memory review</p><h2>Choose what becomes project truth.</h2><span>{pending.length} captured {pending.length===1?'memory':'memories'} awaiting your judgment.</span></div><span className="review-count">{pending.length}</span></div><div className="review-list">{pending.map(item=><div className="review-card" key={item.id}><button className="review-open" onClick={()=>onArtifact(item)}><span className={'memory-glyph '+artifactClass(item.type)}>{artifactIcons[item.type]}</span><span><small>{item.origin==='ai'?'NVIDIA NIM':'Local extraction'} · {Math.round(item.confidence*100)}%</small><strong>{item.title}</strong><em>{item.body}</em>{item.relatedArtifactIds.length>0&&<b><AlertTriangle size={11}/>May change an existing direction</b>}</span><ArrowUpRight size={13}/></button><div className="review-actions" aria-label={'Review '+item.title}><button type="button" onClick={()=>void onReview(item.id,'reject')}>Dismiss</button>{item.relatedArtifactIds.length>0&&<button type="button" className="alongside" onClick={()=>void onReview(item.id,'accept')}><Layers3 size={12}/>Keep alongside</button>}<button type="button" className="accept" onClick={()=>void onReview(item.id,'accept',item.relatedArtifactIds)}><Check size={12}/>{item.relatedArtifactIds.length?'Change direction':'Keep in memory'}</button></div></div>)}</div></section>}
    <div className="memory-toolbar" role="toolbar" aria-label="Filter project memory">{(['all','decision','question','principle','experiment','action'] as const).map(type=><button key={type} aria-pressed={filter===type} className={filter===type?'active':''} onClick={()=>setFilter(type)}>{type==='all'?'All memory':labels[type]}</button>)}<a className="memory-ask" href="/api/studio/export"><Download size={13}/>Export workspace</a></div>
    {visible.length?<div className="memory-story"><div className="memory-period"><span>Now</span><small>Project memory</small></div><div className="memory-items">{visible.map(item=><motion.button layout initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} key={item.id} className={'memory-card '+(item.status==='resolved'?'resolved':'current')} onClick={()=>onArtifact(item)}><span className={'memory-glyph '+artifactClass(item.type)}>{artifactIcons[item.type]}</span><span><small>{item.status==='resolved'?'earlier direction':item.type==='action'?'to-do':item.type} · {Math.round(item.confidence*100)}%</small><strong>{item.title}</strong><em>{item.supersededByArtifactId?'Preserved as an earlier direction. Open to see what changed it.':item.body||'Open this memory to add the reasoning behind it.'}</em></span><ArrowUpRight size={13}/></motion.button>)}</div></div>:<div className="large-empty"><Archive size={22}/><h3>{accepted.length?('No '+(filter==='action'?'to-dos':filter+'s')+' here yet.'):'Memory begins when a conversation leaves something worth keeping.'}</h3><p>{accepted.length?'Choose another lens or return to the conversation and capture what changes.':'Talk through a tension, capture the session, then decide what should become durable project context.'}</p><button onClick={accepted.length?()=>setFilter('all'):onStudio}>{accepted.length?'Show all memory':'Return to the conversation'}<ArrowRight size={12}/></button></div>}
  </main>
}

function HistoryView({data,onSession,onArtifact,onStudio}: {data:Bootstrap;onSession:(id:string)=>void;onArtifact:(artifact:MemoryArtifact)=>void;onStudio:()=>void}){
  const open=(event:TimelineEvent)=>{if(event.artifactId){const item=data.artifacts.find(artifact=>artifact.id===event.artifactId);if(item){onArtifact(item);return}}if(event.sessionId&&data.sessions.some(session=>session.id===event.sessionId))onSession(event.sessionId)};
  return <main id="main-content" tabIndex={-1} className="quiet-surface history-surface"><div className="surface-intro"><p className="eyebrow">Project history</p><h1>What changed,<br/>and why.</h1><p>A continuous record across conversations, references, captures, and edits.</p></div><div className="history-line">
    {data.events.length?data.events.map(event=>{const actionable=Boolean((event.artifactId&&data.artifacts.some(item=>item.id===event.artifactId))||(event.sessionId&&data.sessions.some(item=>item.id===event.sessionId)));const content=<><time dateTime={event.createdAt}>{relativeDate(event.createdAt)}</time><span className="timeline-node">{event.type==='conversation'?<MessageCircleMore size={13}/>:event.type==='reference'?<Link2 size={13}/>:<Layers3 size={13}/>}</span><span><strong>{event.title}</strong><small>{event.detail}</small></span></>;return actionable?<motion.button initial={{opacity:0,x:-6}} animate={{opacity:1,x:0}} key={event.id} className="history-moment" onClick={()=>open(event)}>{content}<ArrowUpRight size={13}/></motion.button>:<motion.div initial={{opacity:0}} animate={{opacity:1}} key={event.id} className="history-moment static">{content}<span/></motion.div>}):<div className="large-empty"><History size={22}/><h3>The record begins with your first move.</h3><p>Start a conversation, add a reference, or capture a direction. History will preserve what changed and where it came from.</p><button onClick={onStudio}>Begin in the conversation<ArrowRight size={12}/></button></div>}
  </div></main>
}

function DialogShell({children,onClose,wide=false,label='Dialog'}: {children:ReactNode;onClose:()=>void;wide?:boolean;label?:string}){
  const ref=useRef<HTMLElement>(null);
  useEffect(()=>{
    const previous=document.activeElement as HTMLElement|null;const node=ref.current;if(!node)return;
    const focusable=()=>Array.prototype.slice.call(node.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')) as HTMLElement[];
    window.setTimeout(()=>{if(!node.contains(document.activeElement))(focusable()[0]||node).focus()},0);
    const key=(event:globalThis.KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();onClose();return}if(event.key!=='Tab')return;const items=focusable();if(!items.length){event.preventDefault();node.focus();return}const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};
    node.addEventListener('keydown',key);return()=>{node.removeEventListener('keydown',key);previous?.focus()};
  },[onClose]);
  return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.section ref={ref} role="dialog" aria-modal="true" aria-label={label} tabIndex={-1} className={'product-modal '+(wide?'wide':'')} initial={{opacity:0,y:12,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:8}} onMouseDown={event=>event.stopPropagation()}>{children}</motion.section></motion.div>
}

function SimpleDialog({type,data,onClose,onDone}: {type:Exclude<Dialog,'settings'>;data:Bootstrap;onClose:()=>void;onDone:(value:any)=>Promise<void>|void}){
  const [name,setName]=useState('');const [description,setDescription]=useState('');const [url,setUrl]=useState('');const [conversationText,setConversationText]=useState('');const [color,setColor]=useState(colors[0]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const labels={project:['New project','Give a new body of work its own memory.'],session:['New conversation','Start a clean thread inside '+data.project.name+'.'],source:['Add project source','Connect a reference that should stay nearby.'],import:['Import conversation','Paste an exported ChatGPT, Claude, or other AI conversation.']} as const;
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');const cleanName=name.trim();const cleanText=conversationText.trim();if(type!=='import'&&!cleanName){setError('Give this '+(type==='source'?'source':type)+' a name before continuing.');return}if(type==='import'&&!cleanText){setError('Paste the conversation you want to bring into this project.');return}if(type==='source'&&url.trim()){try{const parsed=new URL(url.trim());if(!['http:','https:'].includes(parsed.protocol))throw new Error()}catch{setError('Use a complete web address beginning with http:// or https://.');return}}setSaving(true);try{
    if(type==='project')await onDone(await studioApi.createProject({name:cleanName,description,color}));
    if(type==='session')await onDone(await studioApi.createSession(data.project.id,cleanName));
    if(type==='source'){const lower=url.toLowerCase();await onDone(await studioApi.addSource({projectId:data.project.id,title:cleanName,url:url.trim(),note:description.trim(),type:lower.includes('github')?'github':lower.includes('figma')?'figma':'link'}))}
    if(type==='import')await onDone(await studioApi.importText({projectId:data.project.id,title:cleanName||'Imported conversation',text:cleanText}));
  }catch{setError('That could not be saved just now. Nothing was lost—check the details and try again.')}finally{setSaving(false)}};
  const disabled=saving||(type==='import'?!conversationText.trim():!name.trim());
  const action=type==='project'?'Create project':type==='session'?'Start conversation':type==='source'?'Add source':'Import conversation';
  return <DialogShell onClose={onClose} wide={type==='import'} label={labels[type][0]}><form onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">{type}</p><h2>{labels[type][0]}</h2><span>{labels[type][1]}</span></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={17}/></button></div>
    <label><span>{type==='session'||type==='import'?'Title':'Name'}</span><input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder={type==='project'?'Project name':type==='source'?'Reference title':'Conversation title'}/></label>
    {type==='project'&&<><label><span>Description</span><textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="What is this project trying to understand?"/></label><div className="color-picker" role="group" aria-label="Project color">{colors.map((item,index)=><button type="button" key={item} aria-label={'Choose project color '+(index+1)} aria-pressed={color===item} className={color===item?'active':''} style={{background:item}} onClick={()=>setColor(item)}/>)}</div></>}
    {type==='source'&&<><label><span>URL <em>optional</em></span><input inputMode="url" value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://…"/></label><label><span>Why it matters</span><textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Leave a note for future you."/></label></>}
    {type==='import'&&<label><span>Conversation text</span><textarea className="import-area" value={conversationText} onChange={event=>setConversationText(event.target.value)} placeholder={'You: …\n\nAssistant: …'}/></label>}
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="text-button" onClick={onClose}>Cancel</button><button type="submit" className="save-memory" disabled={disabled}>{saving?<Loader2 className="spin" size={13}/>:<Plus size={13}/>} {action}</button></div>
  </form></DialogShell>
}

function SettingsDialog({data,onClose,onProject,onSelectProject,onNewProject,onDeleteProject,onOnboarding,onReset}: {data:Bootstrap;onClose:()=>void;onProject:(project:StudioProject)=>Promise<void>|void;onSelectProject:(id:string)=>Promise<void>|void;onNewProject:()=>void;onDeleteProject:(id:string)=>Promise<void>|void;onOnboarding:()=>void;onReset:(bootstrap:Bootstrap,warning?:string)=>Promise<void>|void}){
  const cloud=data.storageMode==='vercel-blob';
  const [name,setName]=useState(data.project.name);const [description,setDescription]=useState(data.project.description);const [color,setColor]=useState(data.project.color);
  const [saving,setSaving]=useState(false);const [confirmingDelete,setConfirmingDelete]=useState(false);const [confirmingReset,setConfirmingReset]=useState(false);const [clearConnections,setClearConnections]=useState(!cloud);const [resetting,setResetting]=useState(false);const [error,setError]=useState('');
  const [diagnostics,setDiagnostics]=useState<Diagnostics|null>(null);const [checking,setChecking]=useState(false);const [diagnosticError,setDiagnosticError]=useState('');
  const runDiagnostics=useCallback(async(testAI=false)=>{setChecking(true);try{setDiagnostics(await studioApi.diagnostics(testAI))}catch(err:any){setError(err.message||'Connection checks are unavailable. The rest of the workspace is unchanged.')}finally{setChecking(false)}},[]);
  useEffect(()=>{void runDiagnostics(false)},[runDiagnostics]);
  const save=async()=>{if(!name.trim())return;setSaving(true);setError('');try{await onProject(await studioApi.updateProject(data.project.id,{name:name.trim(),description:description.trim(),color}));onClose()}catch(err:any){setError(err.message||'Changes could not be saved. Your earlier project details are still intact.')}finally{setSaving(false)}};
  const remove=async()=>{setSaving(true);setError('');try{await onDeleteProject(data.project.id)}catch(err:any){setError(err.message||'This project could not be removed. Nothing changed.');setSaving(false)}};
  const reset=async()=>{setResetting(true);setError('');try{const result=await studioApi.resetStudio(cloud?false:clearConnections);localStorage.removeItem('creative-memory-onboarding-v1');localStorage.removeItem('remainder-onboarding-v2');await onReset(result.bootstrap,result.warning)}catch(err:any){setError(err.message||'Remainder could not begin again. Your existing projects are unchanged.');setResetting(false)}};
  const diagnosticItems=diagnostics?[{label:'Project memory',ok:diagnostics.storage.ok,detail:diagnostics.storage.detail},{label:'AI conversation',ok:diagnostics.ai.ok,detail:diagnostics.ai.detail},{label:'MCP access',ok:diagnostics.mcp.ok,detail:diagnostics.mcp.detail}]:[];
  return <DialogShell onClose={onClose} wide label="Settings"><div className="modal-heading"><div><p className="eyebrow">Personal workspace</p><h2>Settings</h2><span>Manage projects, verify connections, and control the memory you own.</span></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close settings"><X size={17}/></button></div>
    <div className="settings-layout">
      <section className="settings-section project-manager"><div className="settings-section-heading"><div><span>Projects</span><h3>Your workspace</h3></div><button type="button" className="small-action" onClick={onNewProject}><Plus size={12}/>New project</button></div>
        <div className="project-manager-list">{data.projects.map(project=><div className={project.id===data.project.id?'project-manager-row active':'project-manager-row'} key={project.id}><span className="project-sigil" style={{'--project-color':project.color} as CSSProperties}>{project.name[0]}</span><span><strong>{project.name}</strong><small>{project.description||'No description yet.'}</small></span>{project.id===data.project.id?<em>Current</em>:<button type="button" onClick={()=>void onSelectProject(project.id)}>Open</button>}</div>)}</div>
      </section>
      <section className="settings-section"><div className="settings-section-heading"><div><span>Edit current project</span><h3>{data.project.name}</h3></div><small>{cloud?'Private cloud memory':'Saved on this computer'}</small></div>
        <label><span>Project name</span><input value={name} onChange={event=>setName(event.target.value)}/></label><label><span>Project description</span><textarea value={description} onChange={event=>setDescription(event.target.value)}/></label>
        <div className="color-picker settings-colors" role="group" aria-label="Project color">{colors.map((item,index)=><button type="button" key={item} aria-label={'Choose project color '+(index+1)} aria-pressed={color===item} className={color===item?'active':''} style={{background:item}} onClick={()=>setColor(item)}/>)}</div>
        {error&&!confirmingReset&&<p className="form-error" role="alert">{error}</p>}<div className="settings-row-actions split"><div>{!confirmingDelete?<button type="button" className="danger-button" disabled={data.projects.length===1} title={data.projects.length===1?'A workspace needs at least one project.':''} onClick={()=>setConfirmingDelete(true)}><Trash2 size={13}/>Delete project</button>:<span className="delete-confirm"><span>Delete this project and everything inside it?</span><button type="button" className="text-button" onClick={()=>setConfirmingDelete(false)}>Cancel</button><button type="button" className="danger-button confirmed" onClick={remove} disabled={saving}>Delete</button></span>}</div><button type="button" className="save-memory" onClick={save} disabled={saving||!name.trim()}>{saving?<Loader2 className="spin" size={14}/>:<Check size={14}/>}Save changes</button></div>
        {data.projects.length===1&&<p className="settings-note">A workspace keeps one project at minimum. Rename this project, create another, or use Begin again below.</p>}
      </section>
      <section className="settings-section connection-panel"><div className="settings-section-heading"><div><span>Connection health</span><h3>Know what is working</h3></div><button type="button" className="small-action" onClick={()=>void runDiagnostics(true)} disabled={checking}>{checking?<Loader2 className="spin" size={12}/>:<RotateCcw size={12}/>}Run check</button></div>
        {diagnosticItems.length?<div className="diagnostic-list">{diagnosticItems.map(item=><div className={item.ok?'diagnostic-row ok':'diagnostic-row needs-attention'} key={item.label}><span>{item.ok?<Check size={12}/>:<AlertTriangle size={12}/>}</span><div><strong>{item.label}</strong><small>{item.detail}</small></div></div>)}</div>:<p className="settings-note">{checking?'Checking storage and connections…':'Connection details are not available yet.'}</p>}
        {diagnosticError&&<p className="form-error" role="alert">{diagnosticError}</p>}
        <div className="troubleshooting-note"><CircleHelp size={15}/><div><strong>If conversation fails</strong><p>Run this check first. Remainder should fall back to local intelligence when NIM is unavailable. On Vercel, update keys in Project Settings → Environment Variables, redeploy, then run the check again.</p></div></div>
      </section>
      <div className="settings-quick-actions"><a href="/api/studio/export"><Download size={15}/><span><strong>Export workspace backup</strong><small>Download every project, conversation, and memory</small></span></a><button type="button" onClick={onOnboarding}><CircleHelp size={15}/><span><strong>Setup guide</strong><small>Review NVIDIA NIM and MCP setup</small></span></button></div>
      <section className="about-card"><div className="about-heading"><span><BrandMark compact/></span><div><p className="eyebrow">About</p><h3>Remainder</h3></div></div><p>A project-memory workspace where conversations become durable creative context. Keep the decisions, questions, and unfinished threads that change the work—and return to the reasoning, not a pile of transcripts.</p><div className="about-flow"><span>Conversation</span><ArrowRight size={13}/><span>Capture</span><ArrowRight size={13}/><span>Project memory</span></div><div className="about-details"><span>{cloud?'Private Vercel storage':'Local project storage'}</span><span>Optional NVIDIA NIM</span><span>MCP access for other AI tools</span></div></section>
      <section className="danger-zone"><div><small>Fresh start</small><h3>Begin again</h3><p>Permanently remove every project, conversation, memory, source, and history event. A single blank project will be created and onboarding will restart.</p></div>{!confirmingReset?<button type="button" className="reset-button" onClick={()=>setConfirmingReset(true)}><RotateCcw size={14}/>Begin again</button>:<div className="reset-confirm">{!cloud?<label><input type="checkbox" checked={clearConnections} onChange={event=>setClearConnections(event.target.checked)}/><span><strong>Also remove local connection credentials</strong><small>Disconnect NVIDIA NIM and invalidate the current MCP token on this computer.</small></span></label>:<p className="settings-note">Hosted environment variables remain in Vercel. This resets project memory only.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div><button type="button" className="text-button" onClick={()=>{setConfirmingReset(false);setError('')}} disabled={resetting}>Cancel</button><button type="button" className="confirm-reset" onClick={reset} disabled={resetting}>{resetting?<Loader2 className="spin" size={14}/>:<Trash2 size={14}/>}Reset everything</button></div></div>}</section>
    </div>
  </DialogShell>
}

function ArtifactDialog({artifact,data,onClose,onSave,onDelete,onReview,onOpenSession}: {artifact:MemoryArtifact;data:Bootstrap;onClose:()=>void;onSave:(item:MemoryArtifact)=>Promise<void>|void;onDelete:(id:string)=>Promise<void>|void;onReview:ReviewHandler;onOpenSession:(id:string)=>void}){
  const [title,setTitle]=useState(artifact.title);const [body,setBody]=useState(artifact.body);const [type,setType]=useState(artifact.type);const [status,setStatus]=useState(artifact.status);const [saving,setSaving]=useState(false);const [confirmingDelete,setConfirmingDelete]=useState(false);const [error,setError]=useState('');
  const sourceSession=data.sessions.find(item=>item.id===artifact.sessionId);const sourceMessages=sourceSession?.messages.filter(message=>artifact.sourceMessageIds.includes(message.id))||[];const related=data.artifacts.filter(item=>artifact.relatedArtifactIds.includes(item.id));const supersedes=data.artifacts.filter(item=>artifact.supersedesArtifactIds.includes(item.id));const successor=artifact.supersededByArtifactId?data.artifacts.find(item=>item.id===artifact.supersededByArtifactId):null;
  const save=async()=>{if(!title.trim()){setError('Give this memory a title before saving.');return}setSaving(true);setError('');try{await onSave(await studioApi.updateArtifact(artifact.id,{title:title.trim(),body:body.trim(),type,status}))}catch{setError('This memory could not be saved. Your earlier version is still intact.')}finally{setSaving(false)}};
  const remove=async()=>{setSaving(true);setError('');try{await onDelete(artifact.id)}catch{setError('This memory could not be removed. Nothing changed.');setSaving(false)}};
  return <DialogShell onClose={onClose} wide label={'Edit memory: '+artifact.title}><div className="modal-heading"><div><p className="eyebrow">Project memory</p><h2>Edit what the project remembers</h2><span>Confidence {Math.round(artifact.confidence*100)}% · {artifact.sourceMessageIds.length} source {artifact.sourceMessageIds.length===1?'message':'messages'}</span></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={17}/></button></div>
    <div className="artifact-form-row"><label><span>Type</span><select value={type} onChange={event=>setType(event.target.value as ArtifactType)}>{Object.keys(artifactIcons).map(value=><option value={value} key={value}>{value==='action'?'to-do':value}</option>)}</select></label><label><span>Status</span><select value={status} onChange={event=>setStatus(event.target.value as any)}><option>active</option><option>resolved</option><option>archived</option></select></label></div>
    <label><span>Title</span><input value={title} onChange={event=>setTitle(event.target.value)}/></label><label><span>Rationale and context</span><textarea value={body} onChange={event=>setBody(event.target.value)} rows={6}/></label>
    <div className="memory-trust"><span><ShieldCheck size={14}/><strong>{artifact.origin==='ai'?'Extracted by NVIDIA NIM':artifact.origin==='local'?'Extracted locally':'Existing memory'}</strong><small>{artifact.reviewStatus==='accepted'?'Reviewed and included in AI context':artifact.reviewStatus==='pending'?'Waiting for your review':'Dismissed from project context'}</small></span><span><Clock3 size={14}/><strong>{relativeDate(artifact.createdAt)}</strong><small>{sourceSession?.title||'No source conversation'}</small></span></div>
    {artifact.reviewStatus==='pending'&&related.length>0&&<section className="memory-tension"><AlertTriangle size={16}/><div><strong>Added context, or a changed direction?</strong><p>Keep this alongside {related.map(item=>'“'+item.title+'”').join(', ')}, or deliberately mark those memories as earlier direction. Nothing changes automatically.</p><div className="review-actions inline"><button type="button" onClick={()=>void onReview(artifact.id,'reject')}>Dismiss</button><button type="button" className="alongside" onClick={()=>void onReview(artifact.id,'accept')}><Layers3 size={12}/>Keep alongside</button><button type="button" className="accept" onClick={()=>void onReview(artifact.id,'accept',artifact.relatedArtifactIds)}><Check size={12}/>Change direction</button></div></div></section>}{supersedes.length>0&&<section className="memory-lineage current"><Layers3 size={16}/><div><strong>Current direction</strong><p>This superseded {supersedes.map(item=>'“'+item.title+'”').join(', ')}. Earlier memory remains visible in history.</p></div></section>}{successor&&<section className="memory-lineage earlier"><History size={16}/><div><strong>Earlier direction</strong><p>This was superseded by “{successor.title}”. It remains as evidence of how the project changed.</p></div></section>}
    <section className="memory-provenance"><div><p className="eyebrow">Provenance</p>{sourceSession&&<button type="button" onClick={()=>onOpenSession(sourceSession.id)}>Open conversation<ArrowUpRight size={12}/></button>}</div>{sourceMessages.length?sourceMessages.map(message=><blockquote key={message.id}><small>{message.role==='user'?'You':'Remainder'} · {new Date(message.createdAt).toLocaleString()}</small><p>{message.content}</p></blockquote>):<p className="empty-hint">This memory predates message-level provenance. Its project and creation date are still preserved above.</p>}</section>
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions split"><div className="delete-confirm">{!confirmingDelete?<button type="button" className="danger-button" onClick={()=>setConfirmingDelete(true)}><Trash2 size={13}/>Delete</button>:<><span>Remove this memory?</span><button type="button" className="text-button" onClick={()=>setConfirmingDelete(false)}>Cancel</button><button type="button" className="danger-button confirmed" disabled={saving} onClick={remove}>Remove</button></>}</div><div>{artifact.reviewStatus==='pending'&&related.length===0&&<><button type="button" className="text-button" onClick={()=>void onReview(artifact.id,'reject')}>Dismiss</button><button type="button" className="review-accept" onClick={()=>void onReview(artifact.id,'accept')}><Check size={13}/>Keep</button></>}<button type="button" className="text-button" onClick={onClose}>Cancel</button><button type="button" className="save-memory" onClick={save} disabled={saving||!title.trim()}>{saving?<Loader2 className="spin" size={13}/>:<Check size={13}/>}Save memory</button></div></div>
  </DialogShell>
}

function CaptureDialog({state,onClose,onMemory,onReview}: {state:{status:'working'|'done';artifacts:MemoryArtifact[];mode?:string};onClose:()=>void;onMemory:()=>void;onReview:ReviewHandler}){
  const mode=state.mode==='ai'?'NVIDIA NIM':'local extraction';
  return <DialogShell onClose={onClose} wide label={state.status==='working'?'Capturing session':'Session captured'}>{state.status==='working'?<div className="capture-working" aria-live="polite"><div className="capture-path" aria-hidden="true"><span className="active">Conversation</span><i/><span>Judgment</span><i/><span>Memory</span></div><div className="capture-orbit"><span/><BrandMark/></div><h2>Letting the conversation settle…</h2><p>Finding what changed, what matters, and what should stay with this project.</p></div>:<>
    <div className="modal-heading"><div><span className="capture-complete"><CheckCircle2 size={13}/>Session captured · {mode}</span><h2>{state.artifacts.length?'Choose what the project should remember.':'The conversation is captured.'}</h2><span>{state.artifacts.length?'Review each candidate now, or return to the memory inbox later.':'No durable memory was forced from this exchange.'}</span></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={17}/></button></div>
    {state.artifacts.length?<><div className="capture-path complete" aria-label="Conversation captured. Review is ready."><span className="active">Conversation</span><i/><span className="active">Judgment</span><i/><span>Memory</span></div><div className="capture-grid">{state.artifacts.map(item=><motion.div layout initial={{opacity:0,y:10}} animate={{opacity:1,y:0,x:item.reviewStatus==='accepted'?6:0}} transition={{duration:.24}} className={'captured-item '+item.reviewStatus} key={item.id}><span className={'artifact-icon '+artifactClass(item.type)}>{artifactIcons[item.type]}</span><span><small>{item.type==='action'?'to-do':item.type}{item.relatedArtifactIds.length?' · possible change':''}</small><strong>{item.title}</strong><em>{item.body}</em>{item.reviewStatus==='pending'?<span className="capture-review"><button type="button" onClick={()=>void onReview(item.id,'reject')}>Dismiss</button>{item.relatedArtifactIds.length>0&&<button type="button" onClick={()=>void onReview(item.id,'accept')}><Layers3 size={10}/>Alongside</button>}<button type="button" onClick={()=>void onReview(item.id,'accept',item.relatedArtifactIds)}><Check size={11}/>{item.relatedArtifactIds.length?'Change':'Keep'}</button></span>:<b className="capture-reviewed">{item.reviewStatus==='accepted'?(item.supersedesArtifactIds.length?'Changed the current direction':'Kept in memory'):'Dismissed'}</b>}</span></motion.div>)}</div></>:<div className="large-empty capture-empty"><Layers3 size={20}/><h3>Some conversations are useful without becoming memory.</h3><p>Keep talking, or state the decision, question, or next action more directly before capturing again.</p></div>}
    <div className="modal-actions"><button type="button" className="text-button" onClick={onClose}>Keep talking</button>{state.artifacts.length>0&&<button type="button" className="save-memory" onClick={onMemory}><Archive size={13}/>View project memory</button>}</div>
  </>}</DialogShell>
}

const searchGroup=(result:SearchResult)=>{
  if(result.kind==='project')return 'Projects';
  if(result.kind==='conversation')return 'Conversations';
  if(result.kind==='history')return 'History';
  if(result.kind==='source')return 'Sources';
  if(result.artifactType==='decision')return 'Decisions';
  if(result.artifactType==='question')return 'Questions';
  if(result.artifactType==='idea'||result.artifactType==='experiment')return 'Ideas';
  if(result.artifactType==='action')return 'To-dos';
  return 'Memory';
};
const searchGroupOrder=['Projects','Decisions','Questions','Ideas','To-dos','Conversations','Memory','History','Sources'];

function SearchDialog({onClose,onResult}: {onClose:()=>void;onResult:(result:SearchResult)=>void}){
  const [query,setQuery]=useState('');const [results,setResults]=useState<SearchResult[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [active,setActive]=useState(0);
  const buttons=useRef<Array<HTMLButtonElement|null>>([]);const modal=useRef<HTMLElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const node=modal.current;if(!node)return;const focusable=()=>Array.prototype.slice.call(node.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled])')) as HTMLElement[];const key=(event:globalThis.KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();onClose();return}if(event.key!=='Tab')return;const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};node.addEventListener('keydown',key);return()=>{node.removeEventListener('keydown',key);if(previous?.isConnected)previous.focus()}},[onClose]);
  const run=useCallback(async(value:string,alive?:()=>boolean,signal?:AbortSignal)=>{setLoading(true);setError('');try{const response=await studioApi.search(value,undefined,signal);if(!alive||alive()){setResults(response.results);setActive(0)}}catch{if(signal?.aborted)return;if(!alive||alive())setError('Search paused for a moment. Your memory is safe—try again.')}finally{if(!signal?.aborted&&(!alive||alive()))setLoading(false)}},[]);
  useEffect(()=>{if(!query.trim()){setResults([]);setError('');setLoading(false);return}let current=true;const controller=new AbortController();const timer=window.setTimeout(()=>void run(query,()=>current,controller.signal),120);return()=>{current=false;controller.abort();window.clearTimeout(timer)}},[query,run]);
  const groups=useMemo(()=>searchGroupOrder.map(label=>({label,items:results.filter(result=>searchGroup(result)===label)})).filter(group=>group.items.length),[results]);
  const ordered=useMemo(()=>groups.flatMap(group=>group.items),[groups]);
  useEffect(()=>{buttons.current[active]?.scrollIntoView({block:'nearest'})},[active]);
  const key=(event:ReactKeyboardEvent<HTMLInputElement>)=>{if(event.key==='ArrowDown'){event.preventDefault();setActive(value=>Math.min(value+1,ordered.length-1))}else if(event.key==='ArrowUp'){event.preventDefault();setActive(value=>Math.max(value-1,0))}else if(event.key==='Enter'&&ordered[active]){event.preventDefault();onResult(ordered[active])}};
  return <motion.div className="modal-backdrop search-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.section ref={modal} role="dialog" aria-modal="true" aria-label="Search Remainder" className="search-modal" onMouseDown={event=>event.stopPropagation()} initial={{opacity:0,y:-10,scale:.99}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-6}}>
    <div className="search-input">{loading?<Loader2 className="spin" size={17}/>:<Search size={17}/>}<input autoFocus aria-label="Search every project" aria-controls="studio-search-results" value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={key} placeholder="Search every project, memory, conversation…"/><kbd>Esc</kbd></div>
    <div id="studio-search-results" className="search-results" aria-live="polite" aria-busy={loading}>
      {!query&&<div className="search-teaching"><Search size={18}/><div><strong>Recover the thought, not just the title.</strong><p>Search projects, decisions, questions, ideas, to-dos, conversations, references, and the history around them.</p></div></div>}
      {error&&<div className="search-error"><p>{error}</p><button onClick={()=>void run(query)}>Try again</button></div>}
      {!error&&groups.map(group=><section className="search-group" key={group.label}><div><span>{group.label}</span><small>{group.items.length}</small></div>{group.items.map(result=>{const index=ordered.indexOf(result);return <button ref={node=>{buttons.current[index]=node}} className={active===index?'active':''} key={result.kind+result.id} onMouseEnter={()=>setActive(index)} onClick={()=>onResult(result)}><span>{result.kind==='project'?<Layers3 size={15}/>:result.kind==='conversation'?<MessageCircleMore size={15}/>:result.kind==='source'?<Link2 size={15}/>:result.kind==='history'?<History size={15}/>:<Layers3 size={15}/>}</span><span><strong>{result.title}</strong><small>{result.snippet||result.meta}</small><em>{result.projectName} · {result.meta}</em></span><ArrowRight size={13}/></button>})}</section>)}
      {query&&!loading&&!error&&!results.length&&<div className="search-empty"><Search size={18}/><strong>No thread matches that phrase yet.</strong><p>Try a shorter fragment, a project name, or the language you remember using in the conversation.</p></div>}
    </div>
    <footer className="search-footer"><span><kbd>↑</kbd><kbd>↓</kbd> Move</span><span><kbd>Enter</kbd> Open</span><span><kbd>Esc</kbd> Close</span></footer>
  </motion.section></motion.div>
}

type ToastState={message:string;actionLabel?:string;onAction?:()=>Promise<void>|void};

export default function App(){
  const [surface,setSurface]=useState<Surface>('studio');const [data,setData]=useState<Bootstrap|null>(null);const [session,setSession]=useState<StudioSession|null>(null);
  const [loading,setLoading]=useState(true);const [fatalError,setFatalError]=useState('');const [thinking,setThinking]=useState(false);const [dialog,setDialog]=useState<Dialog>(null);const [search,setSearch]=useState(false);
  const [artifact,setArtifact]=useState<MemoryArtifact|null>(null);const [onboarding,setOnboarding]=useState(()=>localStorage.getItem('remainder-onboarding-v2')!=='complete');const [capture,setCapture]=useState<{status:'working'|'done';artifacts:MemoryArtifact[];mode?:string}|null>(null);const [toast,setToast]=useState<ToastState|null>(null);
  const toastTimer=useRef<number|undefined>(undefined);const loadSequence=useRef(0);const captureShortcut=useRef<()=>void>(()=>undefined);
  const showToast=useCallback((message:string,actionLabel?:string,onAction?:()=>Promise<void>|void)=>{window.clearTimeout(toastTimer.current);setToast({message,actionLabel,onAction});toastTimer.current=window.setTimeout(()=>setToast(null),actionLabel?5200:3200)},[]);
  useEffect(()=>()=>window.clearTimeout(toastTimer.current),[]);
  const load=useCallback(async(projectId?:string,sessionId?:string)=>{const sequence=++loadSequence.current;setLoading(true);setFatalError('');try{const next=await studioApi.bootstrap(projectId);const nextSession=sessionId?await studioApi.getSession(sessionId):next.activeSession;if(sequence!==loadSequence.current)return null;setData(next);setSession(nextSession);localStorage.setItem(ACTIVE_PROJECT_KEY,next.project.id);return next}catch(error:any){if(sequence!==loadSequence.current)return null;const raw=String(error?.message||'');const storageIssue=/cloud|blob|storage/i.test(raw);const message=storageIssue?'Remainder cannot reach its private project memory. Connect Vercel Blob, redeploy, then try again.':'Remainder could not reach its project memory. Check the connection, then try again.';setFatalError(message);showToast(message);return null}finally{if(sequence===loadSequence.current)setLoading(false)}},[showToast]);
  useEffect(()=>{void load(localStorage.getItem(ACTIVE_PROJECT_KEY)||undefined)},[load]);

  const selectProject=async(id:string)=>{if(thinking){showToast('Let this response finish before changing projects.');return}try{const next=await load(id);if(next)setSurface('studio')}catch{showToast('That project could not be opened. Your current work is still here.')}};
  const selectSession=async(id:string)=>{if(thinking){showToast('Let this response finish before changing conversations.');return}try{setSession(await studioApi.getSession(id));setSurface('studio')}catch{showToast('That conversation could not be opened. Try again in a moment.')}};
  const send=async(text:string):Promise<boolean>=>{if(!session||!data)return false;const startingSession=session;const startingProject=data.project.id;const temp={id:'temp_'+Date.now(),role:'user' as const,content:text,createdAt:new Date().toISOString(),citedArtifactIds:[]};setSession(current=>current?.id===startingSession.id?{...current,messages:[...current.messages,temp]}:current);setThinking(true);try{const result=await studioApi.sendMessage(startingSession.id,text);setSession(current=>current?.id===startingSession.id?{...current,messages:[...current.messages.filter(message=>message.id!==temp.id),result.user,result.assistant],updatedAt:result.assistant.createdAt}:current);const fresh=await studioApi.bootstrap(startingProject);setData(current=>current?.project.id===startingProject?fresh:current);if(result.mode==='local')showToast('Local intelligence responded. You can verify NVIDIA NIM in Settings.');return true}catch(err:any){setSession(current=>current?.id===startingSession.id?startingSession:current);showToast((err?.message||'The response did not arrive.')+' Your draft is still in the composer.');return false}finally{setThinking(false)}};
  const captureSession=async()=>{if(!session||thinking||!session.messages.length)return;const startingSession=session;const startingProject=data?.project.id;setCapture({status:'working',artifacts:[]});try{const result=await studioApi.capture(startingSession.id);setCapture(current=>current?{status:'done',artifacts:result.artifacts,mode:result.mode}:null);if(startingProject){const fresh=await studioApi.bootstrap(startingProject);setData(current=>current?.project.id===startingProject?fresh:current)}const refreshed=await studioApi.getSession(startingSession.id);setSession(current=>current?.id===startingSession.id?refreshed:current)}catch{setCapture(null);showToast('The session could not be captured. The conversation is still intact—try again.')}};
  const completeDialog=async(value:any)=>{const previous=dialog;if(previous==='project')await load(value.project.id,value.session.id);else if(previous==='session'||previous==='import'){await load(data?.project.id,value.id);setSurface('studio')}else if(previous==='source'){await load(data?.project.id,session?.id);showToast('Source added to project context.')}setDialog(null)};
  const saveArtifact=async(_item:MemoryArtifact)=>{setArtifact(null);await load(data?.project.id,session?.id);showToast('Project memory updated.')};
  const reviewArtifact=async(id:string,action:'accept'|'reject',supersedeIds:string[]=[])=>{const previous=data?.artifacts.find(item=>item.id===id)||capture?.artifacts.find(item=>item.id===id)||artifact;if(!previous)return;try{const reviewed=await studioApi.reviewArtifact(id,action,supersedeIds);setArtifact(current=>current?.id===id?reviewed:current);setCapture(current=>current?{...current,artifacts:current.artifacts.map(item=>item.id===id?reviewed:item)}:current);await load(data?.project.id,session?.id);const restoreAction=previous.reviewStatus==='pending'?'pending':previous.reviewStatus==='accepted'?'accept':'reject';showToast(action==='accept'?(supersedeIds.length?'Direction updated. Earlier memory remains in history.':'Memory joined the project context.'):'Memory dismissed.','Undo',async()=>{const restored=await studioApi.reviewArtifact(id,restoreAction,restoreAction==='accept'?previous.supersedesArtifactIds:[]);setArtifact(current=>current?.id===id?restored:current);setCapture(current=>current?{...current,artifacts:current.artifacts.map(item=>item.id===id?restored:item)}:current);await load(previous.projectId,session?.id);showToast('Review restored.')})}catch{showToast('That review choice did not save. The memory is unchanged—try again.')}};
  const deleteProject=async(id:string)=>{const removed=await studioApi.deleteProject(id);setDialog(null);await load(removed.activeProjectId);setSurface('studio');showToast('Project deleted.','Undo',async()=>{const restored=await studioApi.restoreProject(removed.snapshot);await load(restored.project.id,restored.activeSession?.id);showToast('Project restored.')})};
  const applyReset=async(next:Bootstrap,warning?:string)=>{setData(next);setSession(next.activeSession);setSurface('studio');setDialog(null);setArtifact(null);setCapture(null);setOnboarding(true);localStorage.setItem(ACTIVE_PROJECT_KEY,next.project.id);showToast(warning||'A fresh workspace is ready.')};
  const deleteArtifact=async(id:string)=>{try{const removed=await studioApi.deleteArtifact(id);setArtifact(null);await load(data?.project.id,session?.id);showToast('Memory removed.','Undo',async()=>{await studioApi.restoreArtifact(removed.artifact);await load(removed.artifact.projectId,session?.id);showToast('Memory restored.')})}catch{throw new Error('Memory could not be removed')}};
  const openResult=async(result:SearchResult)=>{setSearch(false);if(result.kind==='source'&&result.url){window.open(result.url,'_blank','noopener,noreferrer');return}try{const next=await studioApi.bootstrap(result.projectId);setData(next);setSession(next.activeSession);localStorage.setItem(ACTIVE_PROJECT_KEY,next.project.id);
    if(result.kind==='project'){setSurface('studio');return}
    if(result.kind==='conversation'&&result.sessionId){setSession(await studioApi.getSession(result.sessionId));setSurface('studio');return}
    if(result.kind==='artifact'){const item=next.artifacts.find(candidate=>candidate.id===result.id);if(item){setArtifact(item);setSurface('memory');return}}
    if(result.kind==='history'){const item=result.artifactId?next.artifacts.find(candidate=>candidate.id===result.artifactId):undefined;if(item){setArtifact(item);setSurface('history');return}if(result.sessionId){setSession(await studioApi.getSession(result.sessionId));setSurface('studio');return}setSurface('history');return}
    showToast('That item is no longer part of the project. Search has refreshed.')
  }catch{showToast('That result could not be opened. Your place is unchanged.')}};
  captureShortcut.current=()=>{void captureSession()};
  useEffect(()=>{const key=(event:globalThis.KeyboardEvent)=>{if(document.querySelector('[aria-modal="true"]'))return;if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearch(true)}if((event.metaKey||event.ctrlKey)&&event.shiftKey&&event.key.toLowerCase()==='s'){event.preventDefault();captureShortcut.current()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
  const runToastAction=async()=>{const action=toast?.onAction;if(!action)return;window.clearTimeout(toastTimer.current);setToast(null);try{await action()}catch{showToast('Undo could not be completed. Try the original action again.')}};
  if(loading&&!data)return <div className="app-loading" role="status" aria-live="polite"><BrandMark aria-label="Remainder"/><Loader2 className="spin" size={18}/><span>Returning to the work…</span></div>;
  if(!data){const cloudProblem=/cloud|blob/i.test(fatalError);return <main className="deployment-repair"><section><BrandMark aria-label="Remainder"/><p className="eyebrow">A calm repair</p><h1>{cloudProblem?'Remainder needs its private memory.':'Remainder could not open just yet.'}</h1><p>{fatalError||'The application API is not ready yet.'}</p>{cloudProblem?<ol><li>Connect a <strong>Private Vercel Blob</strong> store to this project.</li><li>Redeploy the latest commit so the API receives its storage credentials.</li><li>Open <code>/api/health</code> and confirm that it returns JSON.</li></ol>:<p className="repair-note">Confirm the latest deployment finished successfully, then retry. Existing project memory has not been changed.</p>}<div><button onClick={()=>void load()}><RotateCcw size={14}/>Try again</button>{cloudProblem&&<a href="https://vercel.com/dashboard" target="_blank" rel="noreferrer">Open Vercel dashboard<ArrowUpRight size={13}/></a>}</div><small>Local development stores memory in .memory/studio.json. Vercel uses your private Blob store.</small></section></main>}
  return <div className="app-shell" aria-busy={loading}><a className="skip-link" href="#main-content">Skip to project content</a><Sidebar data={data} surface={surface} onSurface={setSurface} onProject={id=>void selectProject(id)} onNewProject={()=>setDialog('project')} onSettings={()=>setDialog('settings')}/><div className="workspace-shell"><Topbar data={data} session={session} onSearch={()=>setSearch(true)} onSettings={()=>setDialog('settings')} onHelp={()=>setOnboarding(true)} onProject={id=>void selectProject(id)} onNewProject={()=>setDialog('project')}/><AnimatePresence mode="wait"><motion.div key={surface} className="surface-wrap" initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-3}}>
    {surface==='studio'&&<StudioView data={data} session={session} thinking={thinking} onSend={send} onCapture={()=>void captureSession()} onSession={id=>void selectSession(id)} onNewSession={()=>setDialog('session')} onImport={()=>setDialog('import')} onSource={()=>setDialog('source')} onArtifact={setArtifact} onMemory={()=>setSurface('memory')} onProject={id=>void selectProject(id)}/>}
    {surface==='memory'&&<MemoryView data={data} onArtifact={setArtifact} onReview={(id,action)=>void reviewArtifact(id,action)} onStudio={()=>setSurface('studio')}/>}
    {surface==='history'&&<HistoryView data={data} onSession={id=>void selectSession(id)} onArtifact={setArtifact} onStudio={()=>setSurface('studio')}/>}
  </motion.div></AnimatePresence></div>
  <AnimatePresence>
    {dialog&&dialog!=='settings'&&<SimpleDialog type={dialog} data={data} onClose={()=>setDialog(null)} onDone={completeDialog}/>}
    {dialog==='settings'&&<SettingsDialog data={data} onClose={()=>setDialog(null)} onProject={async()=>{await load(data.project.id,session?.id);showToast('Project details updated.')}} onSelectProject={async id=>{setDialog(null);await selectProject(id)}} onNewProject={()=>setDialog('project')} onDeleteProject={deleteProject} onOnboarding={()=>{setDialog(null);setOnboarding(true)}} onReset={applyReset}/>}
    {artifact&&<ArtifactDialog artifact={artifact} data={data} onClose={()=>setArtifact(null)} onSave={saveArtifact} onDelete={deleteArtifact} onReview={reviewArtifact} onOpenSession={id=>{setArtifact(null);void selectSession(id)}}/>}
    {capture&&<CaptureDialog state={capture} onClose={()=>setCapture(null)} onMemory={()=>{setCapture(null);setSurface('memory')}} onReview={(id,action)=>void reviewArtifact(id,action)}/>}
    {search&&<SearchDialog onClose={()=>setSearch(false)} onResult={result=>void openResult(result)}/>}
    {onboarding&&<Onboarding data={data} onClose={()=>setOnboarding(false)} onConfigured={()=>load(data.project.id,session?.id)}/>}
    {toast&&<motion.div className="toast" role="status" aria-live="polite" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:6}}><span>{toast.message}</span>{toast.actionLabel&&<button onClick={()=>void runToastAction()}>{toast.actionLabel}</button>}</motion.div>}
  </AnimatePresence></div>
}
